// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace XModelBuilder.Demo.Shop.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BestellingPlaatsenFeature : object, Xunit.IClassFixture<BestellingPlaatsenFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("nl"), "Features", "Bestelling plaatsen", "    Als klant wil ik een bestelling kunnen plaatsen\r\n    zodat ik producten uit d" +
                "e catalogus kan kopen.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BestellingPlaatsen.feature"
#line hidden
        
        public BestellingPlaatsenFeature(BestellingPlaatsenFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Klant plaatst een geldige bestelling")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling plaatsen")]
        [Xunit.TraitAttribute("Description", "Klant plaatst een geldige bestelling")]
        public async global::System.Threading.Tasks.Task KlantPlaatstEenGeldigeBestelling()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Klant plaatst een geldige bestelling", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
                global::Reqnroll.Table table1 = new global::Reqnroll.Table(new string[] {
                            "Veld",
                            "Waarde"});
                table1.AddRow(new string[] {
                            "Lines[0].Sku",
                            "SKU-PHONE-1"});
                table1.AddRow(new string[] {
                            "Lines[0].Quantity",
                            "2"});
#line 8
    await testRunner.WhenAsync("ik de volgende bestelling plaats:", ((string)(null)), table1, "Als ");
#line hidden
#line 12
    await testRunner.ThenAsync("wordt de bestelling aangemaakt", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
#line 13
    await testRunner.AndAsync("heeft de bestelling status \"Pending\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 14
    await testRunner.AndAsync("is het totaalbedrag 1000.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bestelling met onvoldoende voorraad wordt geweigerd")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling plaatsen")]
        [Xunit.TraitAttribute("Description", "Bestelling met onvoldoende voorraad wordt geweigerd")]
        public async global::System.Threading.Tasks.Task BestellingMetOnvoldoendeVoorraadWordtGeweigerd()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bestelling met onvoldoende voorraad wordt geweigerd", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 16
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 17
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
                global::Reqnroll.Table table2 = new global::Reqnroll.Table(new string[] {
                            "Veld",
                            "Waarde"});
                table2.AddRow(new string[] {
                            "Lines[0].Sku",
                            "SKU-BOOK-1"});
                table2.AddRow(new string[] {
                            "Lines[0].Quantity",
                            "5"});
#line 18
    await testRunner.WhenAsync("ik de volgende bestelling plaats:", ((string)(null)), table2, "Als ");
#line hidden
#line 22
    await testRunner.ThenAsync("wordt de bestelling geweigerd wegens onvoldoende voorraad", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Een gast mag geen bestelling plaatsen")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling plaatsen")]
        [Xunit.TraitAttribute("Description", "Een gast mag geen bestelling plaatsen")]
        public async global::System.Threading.Tasks.Task EenGastMagGeenBestellingPlaatsen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Een gast mag geen bestelling plaatsen", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 24
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 25
    await testRunner.GivenAsync("ik ben niet ingelogd", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
                global::Reqnroll.Table table3 = new global::Reqnroll.Table(new string[] {
                            "Veld",
                            "Waarde"});
                table3.AddRow(new string[] {
                            "Lines[0].Sku",
                            "SKU-PHONE-1"});
                table3.AddRow(new string[] {
                            "Lines[0].Quantity",
                            "1"});
#line 26
    await testRunner.WhenAsync("ik de volgende bestelling plaats:", ((string)(null)), table3, "Als ");
#line hidden
#line 30
    await testRunner.ThenAsync("word ik afgewezen als niet-geautoriseerd", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Bestelling met kortingscode verlaagt het totaal")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling plaatsen")]
        [Xunit.TraitAttribute("Description", "Bestelling met kortingscode verlaagt het totaal")]
        public async global::System.Threading.Tasks.Task BestellingMetKortingscodeVerlaagtHetTotaal()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Bestelling met kortingscode verlaagt het totaal", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 32
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 33
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
                global::Reqnroll.Table table4 = new global::Reqnroll.Table(new string[] {
                            "Veld",
                            "Waarde"});
                table4.AddRow(new string[] {
                            "Lines[0].Sku",
                            "SKU-PHONE-1"});
                table4.AddRow(new string[] {
                            "Lines[0].Quantity",
                            "1"});
                table4.AddRow(new string[] {
                            "DiscountCode",
                            "WELCOME10"});
#line 34
    await testRunner.WhenAsync("ik de volgende bestelling plaats:", ((string)(null)), table4, "Als ");
#line hidden
#line 39
    await testRunner.ThenAsync("wordt de bestelling aangemaakt", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
#line 40
    await testRunner.AndAsync("is het kortingsbedrag 50.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 41
    await testRunner.AndAsync("is het totaalbedrag 450.00", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BestellingPlaatsenFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BestellingPlaatsenFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
