// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace XModelBuilder.Demo.Shop.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class BestellingUitleverenFeature : object, Xunit.IClassFixture<BestellingUitleverenFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("nl"), "Features", "Bestelling uitleveren", "    Als magazijnmedewerker wil ik betaalde bestellingen verzenden\r\n    en mogen o" +
                "nbetaalde bestellingen of klanten dat niet doen.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BestellingUitleveren.feature"
#line hidden
        
        public BestellingUitleverenFeature(BestellingUitleverenFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Magazijn verzendt een betaalde bestelling")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling uitleveren")]
        [Xunit.TraitAttribute("Description", "Magazijn verzendt een betaalde bestelling")]
        public async global::System.Threading.Tasks.Task MagazijnVerzendtEenBetaaldeBestelling()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Magazijn verzendt een betaalde bestelling", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
#line 8
    await testRunner.AndAsync("ik een betaalde bestelling heb geplaatst voor 1 x \"SKU-PHONE-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 9
    await testRunner.WhenAsync("ik ben ingelogd als magazijnmedewerker \"wendy@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Als ");
#line hidden
#line 10
    await testRunner.AndAsync("ik de bestelling verzend", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 11
    await testRunner.ThenAsync("wordt de verzending geaccepteerd", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
#line 12
    await testRunner.AndAsync("heeft de bestelling status \"Shipped\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Een onbetaalde bestelling kan niet verzonden worden")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling uitleveren")]
        [Xunit.TraitAttribute("Description", "Een onbetaalde bestelling kan niet verzonden worden")]
        public async global::System.Threading.Tasks.Task EenOnbetaaldeBestellingKanNietVerzondenWorden()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Een onbetaalde bestelling kan niet verzonden worden", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 14
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 15
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
#line 16
    await testRunner.AndAsync("ik een bestelling heb geplaatst voor 1 x \"SKU-PHONE-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 17
    await testRunner.WhenAsync("ik ben ingelogd als magazijnmedewerker \"wendy@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Als ");
#line hidden
#line 18
    await testRunner.AndAsync("ik de bestelling verzend", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 19
    await testRunner.ThenAsync("wordt de verzending geweigerd", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Een klant mag geen bestellingen verzenden")]
        [Xunit.TraitAttribute("FeatureTitle", "Bestelling uitleveren")]
        [Xunit.TraitAttribute("Description", "Een klant mag geen bestellingen verzenden")]
        public async global::System.Threading.Tasks.Task EenKlantMagGeenBestellingenVerzenden()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Een klant mag geen bestellingen verzenden", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 21
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 22
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
#line 23
    await testRunner.AndAsync("ik een betaalde bestelling heb geplaatst voor 1 x \"SKU-PHONE-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 24
    await testRunner.WhenAsync("ik de bestelling verzend", ((string)(null)), ((global::Reqnroll.Table)(null)), "Als ");
#line hidden
#line 25
    await testRunner.ThenAsync("word ik afgewezen als verboden", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await BestellingUitleverenFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await BestellingUitleverenFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
