// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by Reqnroll (https://www.reqnroll.net/).
//      Reqnroll Version:2.0.0.0
//      Reqnroll Generator Version:2.0.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
using Reqnroll;
namespace XModelBuilder.Demo.Shop.IntegrationTests.Features
{
    
    
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class CatalogusEnToegangFeature : object, Xunit.IClassFixture<CatalogusEnToegangFeature.FixtureData>, Xunit.IAsyncLifetime
    {
        
        private global::Reqnroll.ITestRunner testRunner;
        
        private static string[] featureTags = ((string[])(null));
        
        private static global::Reqnroll.FeatureInfo featureInfo = new global::Reqnroll.FeatureInfo(new global::System.Globalization.CultureInfo("nl"), "Features", "Catalogus en toegang", "    Alleen een beheerder mag de catalogus uitbreiden,\r\n    en een klant mag uitsl" +
                "uitend zijn eigen bestellingen inzien.", global::Reqnroll.ProgrammingLanguage.CSharp, featureTags);
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "CatalogusEnToegang.feature"
#line hidden
        
        public CatalogusEnToegangFeature(CatalogusEnToegangFeature.FixtureData fixtureData, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
        }
        
        public static async global::System.Threading.Tasks.Task FeatureSetupAsync()
        {
        }
        
        public static async global::System.Threading.Tasks.Task FeatureTearDownAsync()
        {
        }
        
        public async global::System.Threading.Tasks.Task TestInitializeAsync()
        {
            testRunner = global::Reqnroll.TestRunnerManager.GetTestRunnerForAssembly(featureHint: featureInfo);
            try
            {
                if (((testRunner.FeatureContext != null) 
                            && (testRunner.FeatureContext.FeatureInfo.Equals(featureInfo) == false)))
                {
                    await testRunner.OnFeatureEndAsync();
                }
            }
            finally
            {
                if (((testRunner.FeatureContext != null) 
                            && testRunner.FeatureContext.BeforeFeatureHookFailed))
                {
                    throw new global::Reqnroll.ReqnrollException("Scenario skipped because of previous before feature hook error");
                }
                if ((testRunner.FeatureContext == null))
                {
                    await testRunner.OnFeatureStartAsync(featureInfo);
                }
            }
        }
        
        public async global::System.Threading.Tasks.Task TestTearDownAsync()
        {
            if ((testRunner == null))
            {
                return;
            }
            try
            {
                await testRunner.OnScenarioEndAsync();
            }
            finally
            {
                global::Reqnroll.TestRunnerManager.ReleaseTestRunner(testRunner);
                testRunner = null;
            }
        }
        
        public void ScenarioInitialize(global::Reqnroll.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public async global::System.Threading.Tasks.Task ScenarioStartAsync()
        {
            await testRunner.OnScenarioStartAsync();
        }
        
        public async global::System.Threading.Tasks.Task ScenarioCleanupAsync()
        {
            await testRunner.CollectScenarioErrorsAsync();
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
        {
            try
            {
                await this.TestInitializeAsync();
            }
            catch (System.Exception e1)
            {
                try
                {
                    ((Xunit.IAsyncLifetime)(this)).DisposeAsync();
                }
                catch (System.Exception e2)
                {
                    throw new System.AggregateException("Test initialization failed", e1, e2);
                }
                throw;
            }
        }
        
        async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
        {
            await this.TestTearDownAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Beheerder voegt een product toe")]
        [Xunit.TraitAttribute("FeatureTitle", "Catalogus en toegang")]
        [Xunit.TraitAttribute("Description", "Beheerder voegt een product toe")]
        public async global::System.Threading.Tasks.Task BeheerderVoegtEenProductToe()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Beheerder voegt een product toe", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 6
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 7
    await testRunner.GivenAsync("ik ben ingelogd als beheerder \"admin@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
                global::Reqnroll.Table table5 = new global::Reqnroll.Table(new string[] {
                            "Veld",
                            "Waarde"});
                table5.AddRow(new string[] {
                            "Sku",
                            "SKU-LAPTOP-9"});
                table5.AddRow(new string[] {
                            "Name",
                            "Demo Laptop"});
                table5.AddRow(new string[] {
                            "UnitPrice",
                            "999.99"});
                table5.AddRow(new string[] {
                            "StockQuantity",
                            "5"});
                table5.AddRow(new string[] {
                            "Category",
                            "Laptops"});
#line 8
    await testRunner.WhenAsync("ik het volgende product toevoeg:", ((string)(null)), table5, "Als ");
#line hidden
#line 15
    await testRunner.ThenAsync("wordt het product toegevoegd", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
#line 16
    await testRunner.AndAsync("bevat de catalogus een product met sku \"SKU-LAPTOP-9\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Een klant mag geen product toevoegen")]
        [Xunit.TraitAttribute("FeatureTitle", "Catalogus en toegang")]
        [Xunit.TraitAttribute("Description", "Een klant mag geen product toevoegen")]
        public async global::System.Threading.Tasks.Task EenKlantMagGeenProductToevoegen()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Een klant mag geen product toevoegen", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 18
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 19
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
                global::Reqnroll.Table table6 = new global::Reqnroll.Table(new string[] {
                            "Veld",
                            "Waarde"});
                table6.AddRow(new string[] {
                            "Sku",
                            "SKU-HACK-1"});
                table6.AddRow(new string[] {
                            "Name",
                            "Verboden"});
                table6.AddRow(new string[] {
                            "UnitPrice",
                            "1.00"});
                table6.AddRow(new string[] {
                            "StockQuantity",
                            "1"});
                table6.AddRow(new string[] {
                            "Category",
                            "Books"});
#line 20
    await testRunner.WhenAsync("ik het volgende product toevoeg:", ((string)(null)), table6, "Als ");
#line hidden
#line 27
    await testRunner.ThenAsync("word ik afgewezen als verboden", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [Xunit.SkippableFactAttribute(DisplayName="Een klant ziet de bestellingen van een ander niet")]
        [Xunit.TraitAttribute("FeatureTitle", "Catalogus en toegang")]
        [Xunit.TraitAttribute("Description", "Een klant ziet de bestellingen van een ander niet")]
        public async global::System.Threading.Tasks.Task EenKlantZietDeBestellingenVanEenAnderNiet()
        {
            string[] tagsOfScenario = ((string[])(null));
            global::System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new global::System.Collections.Specialized.OrderedDictionary();
            global::Reqnroll.ScenarioInfo scenarioInfo = new global::Reqnroll.ScenarioInfo("Een klant ziet de bestellingen van een ander niet", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 29
this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((global::Reqnroll.TagHelper.ContainsIgnoreTag(scenarioInfo.CombinedTags) || global::Reqnroll.TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                await this.ScenarioStartAsync();
#line 30
    await testRunner.GivenAsync("ik ben ingelogd als klant \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Gegeven ");
#line hidden
#line 31
    await testRunner.AndAsync("ik een bestelling heb geplaatst voor 1 x \"SKU-PHONE-1\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 32
    await testRunner.WhenAsync("ik ben ingelogd als klant \"bob@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "Als ");
#line hidden
#line 33
    await testRunner.AndAsync("ik de bestellingen opvraag van \"alice@shop.test\"", ((string)(null)), ((global::Reqnroll.Table)(null)), "En ");
#line hidden
#line 34
    await testRunner.ThenAsync("word ik afgewezen als verboden", ((string)(null)), ((global::Reqnroll.Table)(null)), "Dan ");
#line hidden
            }
            await this.ScenarioCleanupAsync();
        }
        
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Reqnroll", "2.0.0.0")]
        [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : object, Xunit.IAsyncLifetime
        {
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.InitializeAsync()
            {
                await CatalogusEnToegangFeature.FeatureSetupAsync();
            }
            
            async global::System.Threading.Tasks.Task Xunit.IAsyncLifetime.DisposeAsync()
            {
                await CatalogusEnToegangFeature.FeatureTearDownAsync();
            }
        }
    }
}
#pragma warning restore
#endregion
